# import = ["~/.cache/wallust/colors-alacritty.toml"]

[window]
dynamic_padding = true
opacity = 0.85

[font]
normal = { family = "JetBrainsMono Nerdfont", style = "Regular"}
size = 11.0
# offset = { x = 12, y = 12 }

[keyboard]
bindings = [
    { key = "Return", mods = "Alt", action = "SpawnNewInstance" },
]
